name: readysafe
description: ReadySafe is an offline-first emergency preparedness companion.
publish_to: none
version: 2.2.0+4

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  crypto: ^3.0.6
  flutter_svg: ^2.2.1
  maplibre_gl: 0.26.2
  path_provider: ^2.1.5
  http: ^1.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/illustrations/
    - assets/maps/
