import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../app/app_scope.dart';
import '../app/localizations.dart';
import '../models/country_profile.dart';
import '../services/emergency_call_service.dart';

class EmergencyScreen extends StatelessWidget {
  const EmergencyScreen({super.key,this.callService});
  final EmergencyCallService? callService;
  IconData _icon(String key){if(key.contains('police'))return Icons.local_police_outlined;if(key.contains('fire'))return Icons.local_fire_department_outlined;if(key.contains('ambulance'))return Icons.emergency_outlined;if(key.contains('poison'))return Icons.science_outlined;if(key.contains('youth'))return Icons.child_care_outlined;if(key.contains('help'))return Icons.support_agent_outlined;return Icons.sos_outlined;}
  @override Widget build(BuildContext context){final t=AppLocalizations.of(context),country=AppScope.of(context).activeCountry!;return Scaffold(appBar:AppBar(title:Text(t.get('emergencies'))),body:ListView(padding:const EdgeInsets.fromLTRB(16,4,16,28),children:[Row(children:[Container(width:44,height:32,alignment:Alignment.center,decoration:BoxDecoration(color:const Color(0xffeef4f5),borderRadius:BorderRadius.circular(10)),child:Text(country.isoCode,style:const TextStyle(fontWeight:FontWeight.w900))),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t.get(country.nameKey),style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text(t.get('emergency_hint'),style:const TextStyle(color:Color(0xff65747a))) ]))]),const SizedBox(height:16),...country.services.map((s)=>_EmergencyCard(service:s,icon:_icon(s.nameKey),callService:callService??DeviceEmergencyCallService())),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.verified_user_outlined,color:Color(0xff087f83)),const SizedBox(width:8),Text(t.get('official_sources'),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16))]),const SizedBox(height:8),...country.sources.map((source)=>ListTile(dense:true,contentPadding:EdgeInsets.zero,title:Text(source.host,style:const TextStyle(fontWeight:FontWeight.w700)),trailing:const Icon(Icons.open_in_new,size:18),onTap:()=>launchUrl(source,mode:LaunchMode.externalApplication))),Text(country.verifiedOn!=null?t.get('verified_on',{'date':country.verifiedOn!.toIso8601String().substring(0,10)}):t.get('numbers_unverified'),style:const TextStyle(fontSize:12,color:Color(0xff65747a))) ])))]));}
}

class _EmergencyCard extends StatelessWidget {const _EmergencyCard({required this.service,required this.icon,required this.callService});final EmergencyService service;final IconData icon;final EmergencyCallService callService;
  @override Widget build(BuildContext context){final t=AppLocalizations.of(context);return Card(margin:const EdgeInsets.only(bottom:9),child:InkWell(borderRadius:BorderRadius.circular(18),onTap:service.isCallable?()=>_confirm(context,t):null,child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:const Color(0xffffe9e9),borderRadius:BorderRadius.circular(14)),child:Icon(icon,color:Theme.of(context).colorScheme.error,size:27)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t.get(service.nameKey),style:const TextStyle(fontSize:16,fontWeight:FontWeight.w900)),Text(t.get(service.descriptionKey),maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:12,color:Color(0xff65747a)))])),const SizedBox(width:8),Column(crossAxisAlignment:CrossAxisAlignment.end,children:[Text(service.number??'—',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900,color:service.isCallable?Theme.of(context).colorScheme.error:Colors.grey)),if(service.isCallable)const Row(children:[Icon(Icons.phone,size:13,color:Color(0xff65747a)),SizedBox(width:3),Text('Appeler',style:TextStyle(fontSize:11,fontWeight:FontWeight.w700,color:Color(0xff65747a)))])])]))));}
  Future<void> _confirm(BuildContext context,AppLocalizations t)async{final number=service.number;if(number==null||!service.isCallable)return;final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(icon:Icon(Icons.phone_in_talk,color:Theme.of(context).colorScheme.error,size:34),title:Text(t.get('call_confirm_title')),content:Text(t.get('call_confirm_body',{'number':number,'service':t.get(service.nameKey)})),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:Text(t.get('cancel'))),FilledButton(style:FilledButton.styleFrom(backgroundColor:Theme.of(context).colorScheme.error),onPressed:()=>Navigator.pop(c,true),child:Text(t.get('call')))]))??false;if(!ok||!context.mounted)return;final launched=await callService.call(number);if(!launched&&context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t.get('call_failed'))));}
}
